name: docs

on:
  push:
    branches:
      - gcam-v6.0

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1.0'

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install libcurl
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev
      
      - name: Restart R
        run: |
          R --vanilla --quiet
          echo 'q()' | R --no-save

      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"), repos = "https://cloud.r-project.org")
          remotes::install_deps(dependencies = TRUE)
          install.packages("pkgdown", type = "binary")
        shell: Rscript {0}

      - name: Install package
        run: R CMD INSTALL .

      - name: Deploy package
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'

      - name: Track file
        run: |
          git add .github/r-depends.rds
          git commit -m "track file"
      
      - name: Rename file
        run: |
          git mv csheet.pdf cheatsheet.pdf
      
      - name: Auto commit
        uses: klau506/git-auto-commit-action@v4
        with:
          branch: gh-pages
          push_options: --force

